/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { HPDCInputs, HPDCOutputs } from '../types';
import { HelpCircle, ChevronDown, ChevronUp } from 'lucide-react';

interface FormulaSheetProps {
  inputs: HPDCInputs;
  outputs: HPDCOutputs;
}

interface FormulaItem {
  id: string;
  name: string;
  symbol: string;
  latex: string;
  unit: string;
  getValue: (out: HPDCOutputs, inp: HPDCInputs) => string;
  getStep: (out: HPDCOutputs, inp: HPDCInputs) => string;
  explanation: string;
}

export const FormulaSheet: React.FC<FormulaSheetProps> = ({ inputs, outputs }) => {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const formulas: FormulaItem[] = [
    {
      id: 'shot-weight',
      name: 'Total Shot Weight',
      symbol: 'W_shot',
      latex: 'W_casting + W_overflow + W_runner',
      unit: 'grams (g)',
      getValue: (out) => `${out.shot_weight.toFixed(2)} g`,
      getStep: (out, inp) => `${inp.w_casting}g (Casting) + ${inp.w_overflow}g (Overflow) + ${inp.w_runner}g (Runner) = ${out.shot_weight.toFixed(2)}g`,
      explanation: 'Determines the total physical dose of metal injected into the molding machinery per cycle.'
    },
    {
      id: 'cavity-vol',
      name: 'Cavity Volume (Part + Overflows)',
      symbol: 'V_cavity',
      latex: '(W_casting + W_overflow) / ρ',
      unit: 'cm³ (cc)',
      getValue: (out) => `${out.cavity_volume.toFixed(2)} cm³`,
      getStep: (out, inp) => `(${inp.w_casting}g + ${inp.w_overflow}g) / ${inp.density} g/cm³ = ${out.cavity_volume.toFixed(2)} cm³`,
      explanation: 'The volume required only for the active product and overflows. This governs fast-filling calculations.'
    },
    {
      id: 'plunger-area',
      name: 'Plunger Area',
      symbol: 'A_plun',
      latex: 'π × (Dp / 2)²',
      unit: 'cm²',
      getValue: (out) => `${out.plunger_area.toFixed(2)} cm²`,
      getStep: (out, inp) => `π × (${inp.plunger_dia} cm / 2)² = 3.14159 × ${Math.pow(inp.plunger_dia / 2, 2).toFixed(2)} = ${out.plunger_area.toFixed(2)} cm²`,
      explanation: 'Cross-sectional Area of the hydraulic plunger tip pushing the metal.'
    },
    {
      id: 'sleeve-capacity',
      name: 'Active Sleeve Capacity',
      symbol: 'C_sleeve',
      latex: 'A_plun × L_sleeve',
      unit: 'cm³ (cc)',
      getValue: (out) => `${out.sleeve_capacity.toFixed(2)} cm³`,
      getStep: (out, inp) => `${out.plunger_area.toFixed(2)} cm² × ${inp.sleeve_length} cm = ${out.sleeve_capacity.toFixed(2)} cm³`,
      explanation: 'Total inner volume capacity of the structural shot sleeve.'
    },
    {
      id: 'fill-ratio',
      name: 'Sleeve metal Filling Ratio',
      symbol: 'F_ratio',
      latex: '(V_shot / C_sleeve) × 100',
      unit: '%',
      getValue: (out) => `${out.filling_ratio.toFixed(2)} %`,
      getStep: (out) => `(${out.shot_volume.toFixed(2)} cm³ / ${out.sleeve_capacity.toFixed(2)} cm³) × 100 = ${out.filling_ratio.toFixed(2)}%`,
      explanation: 'The initial percentage of the sleeve filled with metal. Keeping this between 30% and 55% stops splashing air entrapment.'
    },
    {
      id: 'stroke-fast',
      name: 'Fast-Shot Stroke Length (S2)',
      symbol: 'L_fast',
      latex: 'V_cavity / A_plun',
      unit: 'cm',
      getValue: (out) => `${out.fast_shot_length.toFixed(2)} cm`,
      getStep: (out) => `${out.cavity_volume.toFixed(2)} cm³ / ${out.plunger_area.toFixed(2)} cm² = ${out.fast_shot_length.toFixed(2)} cm`,
      explanation: 'The stroke displacement of the plunger required to force the main component and overflow cavities full.'
    },
    {
      id: 'stroke-slow',
      name: 'Slow-Shot Stroke (S1 switchover)',
      symbol: 'L_slow',
      latex: 'L_s_len - T_biscuit - L_fast',
      unit: 'cm',
      getValue: (out) => `${out.slow_shot_length.toFixed(2)} cm`,
      getStep: (out, inp) => `${inp.sleeve_length} cm (Sleeve) - ${inp.biscuit_thickness} cm (Biscuit) - ${out.fast_shot_length.toFixed(2)} cm (L_fast) = ${out.slow_shot_length.toFixed(2)} cm`,
      explanation: 'Plunger stroke before the fast cavity-fill phase. This marks where the machine switches over (S1 switch).'
    },
    {
      id: 'injection-flow',
      name: 'Actual Injection Flow Rate',
      symbol: 'Q_act',
      latex: 'A_plun × (v_fast × 100)',
      unit: 'cc/s (cm³/s)',
      getValue: (out) => `${Math.round(out.flow_rate_actual)} cc/s`,
      getStep: (out, inp) => `${out.plunger_area.toFixed(2)} cm² × (${inp.fast_shot_speed} m/s × 100 cm/m) = ${out.flow_rate_actual.toFixed(2)} cc/s`,
      explanation: 'The volumetric flow rate generated by the fast shot runner system.'
    },
    {
      id: 'metal-speed',
      name: 'Metal Jet Velocity at Gate',
      symbol: 'V_gate',
      latex: 'Q_act / (A_gate × 100)',
      unit: 'm/s',
      getValue: (out) => `${out.metal_speed_gate.toFixed(2)} m/s`,
      getStep: (out, inp) => `${out.flow_rate_actual.toFixed(2)} cc/s / (${inp.gate_area} cm² × 100) = ${out.metal_speed_gate.toFixed(2)} m/s`,
      explanation: 'The actual peak velocity the molten metal shoots into the mold cavity. Highly critical for surface defects.'
    },
    {
      id: 'gate-width',
      name: 'Recalculated Gate Width',
      symbol: 'W_gate',
      latex: '(A_gate × 100) / t_gate',
      unit: 'mm',
      getValue: (out) => `${out.gate_width.toFixed(1)} mm`,
      getStep: (out, inp) => `(${inp.gate_area} cm² × 100 mm²/cm²) / ${inp.gate_thickness} mm = ${out.gate_width.toFixed(1)} mm`,
      explanation: 'Calculates the spatial continuous feeding width of the runner gate slit at the die entrance.'
    },
    {
      id: 'j-number',
      name: 'Wallace Atomization Number',
      symbol: 'J',
      latex: 't_gate × ρ × V_gate^(1.71)',
      unit: 'dimensionless',
      getValue: (out) => `${Math.round(out.j_actual)}`,
      getStep: (out, inp) => `${inp.gate_thickness} mm × ${inp.density} g/cm³ × (${out.metal_speed_gate.toFixed(2)} m/s)^1.71 = ${Math.round(out.j_actual)}`,
      explanation: 'Wallace Gating constant determines if fluid behaves as atomized mist spray (high J) or splashing jets (low J).'
    },
    {
      id: 'clamp-force',
      name: 'Required Clamping Tonnage',
      symbol: 'F_clamp',
      latex: 'A_proj × P_cast × 0.01',
      unit: 'Tons',
      getValue: (out) => `${out.clamping_required.toFixed(1)} Tons`,
      getStep: (out, inp) => `${inp.projected_area} cm² × ${inp.casting_pressure} MPa × 0.01 = ${out.clamping_required.toFixed(1)} Tons`,
      explanation: 'The minimum machine locking force required to clamp the mold halves shut, resisting cavity separation pressure.'
    },
    {
      id: 'intensifier-pressure',
      name: 'Hydraulic Intensifier Pressure',
      symbol: 'P_hydro',
      latex: 'P_cast / (D_int / D_plun)²',
      unit: 'MPa',
      getValue: (out) => `${out.intensification_pressure.toFixed(2)} MPa`,
      getStep: (out, inp) => `${inp.casting_pressure} MPa / (${inp.intensifier_dia} cm / ${inp.plunger_dia} cm)² = ${out.intensification_pressure.toFixed(2)} MPa`,
      explanation: 'Required peak hydraulic line pressure at the third intensification system to deliver specific metal compaction.'
    }
  ];

  const handleToggle = (id: string) => {
    if (expandedId === id) {
      setExpandedId(null);
    } else {
      setExpandedId(id);
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 p-5 shadow-xl rounded-none" id="formula-sheet">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-sm font-black tracking-wider text-slate-100 uppercase">Interactive Formula & Calculations Sheet</h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Click on any formula row to inspect parameters, variables, symbols, and step-by-step math.
          </p>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse text-xs">
          <thead>
            <tr className="bg-slate-950 border-b border-slate-800 text-slate-400 font-bold uppercase tracking-wider text-[10px]">
              <th className="py-2.5 px-3">Gating Variable</th>
              <th className="py-2.5 px-3">Symbol</th>
              <th className="py-2.5 px-3">Formula</th>
              <th className="py-2.5 px-3">Target Calculated</th>
              <th className="py-2.5 px-3 text-right">Units</th>
              <th className="py-2.5 px-3 w-10"></th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-850">
            {formulas.map((item) => {
              const isExpanded = expandedId === item.id;
              return (
                <React.Fragment key={item.id}>
                  <tr 
                    onClick={() => handleToggle(item.id)}
                    className="hover:bg-slate-950 cursor-pointer transition-colors text-slate-300"
                  >
                    <td className="py-3 px-3 font-bold text-slate-100 text-xs">{item.name}</td>
                    <td className="py-3 px-3"><span className="bg-slate-950 text-slate-400 border border-slate-800 px-1.5 py-0.5 rounded-none font-mono text-[10px] uppercase font-bold">{item.symbol}</span></td>
                    <td className="py-3 px-3"><span className="font-mono text-cyan-400 bg-cyan-950/20 border border-cyan-900/30 rounded-none px-2 py-0.5 inline-block font-semibold">{item.latex}</span></td>
                    <td className="py-3 px-3 font-mono font-black text-cyan-400 text-[12px]">{item.getValue(outputs, inputs)}</td>
                    <td className="py-3 px-3 text-right text-slate-400 font-semibold font-mono">{item.unit}</td>
                    <td className="py-3 px-3 text-right">
                      {isExpanded ? <ChevronUp className="h-4 w-4 text-cyan-500" /> : <ChevronDown className="h-4 w-4 text-slate-500" />}
                    </td>
                  </tr>

                  {isExpanded && (
                    <tr className="bg-slate-950/50">
                      <td colSpan={6} className="py-3 px-5 border-l-4 border-l-cyan-600">
                        <div className="space-y-2">
                          <p className="text-[11px] text-slate-400 leading-relaxed">
                            <span className="font-bold text-slate-200 uppercase tracking-wider text-[10px] block mb-0.5">Explanation:</span> {item.explanation}
                          </p>
                          <div className="flex flex-wrap gap-2 items-center bg-slate-950 p-2.5 rounded-none border border-slate-800 font-mono text-[11px] text-slate-300">
                            <HelpCircle className="h-3.5 w-3.5 text-cyan-500 shrink-0" />
                            <span className="font-bold text-cyan-500 uppercase tracking-wider text-[10px]">Substitution:</span>
                            <span className="text-slate-100">{item.getStep(outputs, inputs)}</span>
                          </div>
                        </div>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
};
